apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster-shop-prod
nameSuffix:
  -prod
commonLabels:
  app: redis-cart

bases:
- ../../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
