apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2022-04-06T18:04:10Z"
  name: pod-reader
  namespace: prometheus
  resourceVersion: "2509636"
  uid: 7ac5c2d9-194d-4cd3-a1b0-666fea896787
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

# kubectl create role pod-reader --verb=get,list,watch --resource=pods --namespace=prometheus -o yaml > 03-rolebinding.yamlapiVersion: rbac.authorization.k8s.io/v1
---
kind: RoleBinding
metadata:
  creationTimestamp: "2022-04-06T18:05:35Z"
  name: carol-pod
  namespace: default
  resourceVersion: "2509974"
  uid: 4bc3c906-4b21-4319-b183-1a6bedf69bff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus

# kubectl create rolebinding carol-pod --role=pod-reader --serviceaccount=prometheus:carol -o yaml >> 03-rolebinding.yaml