---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2022-04-06T18:19:52Z"
  name: pod-reader
  resourceVersion: "2513675"
  uid: 81c5fc62-67e7-44e7-9011-aa4062d4aef6
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch


# kubectl create clusterrole pod-reader --verb=get,list,watch --resource=pods --namespace=prometheus -o yaml > 03-rolebinding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-04-06T18:38:41Z"
  name: carol-pod
  resourceVersion: "2518590"
  uid: 6864728e-4a18-4264-b559-6a56dbc20ae1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader

# kubectl create clusterrolebinding carol-pod --clusterrole=pod-reader -o yaml >> 03-rolebinding.yaml