apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-04-06T17:47:29Z"
  name: bob-admin
  resourceVersion: "2505248"
  uid: 80e36861-f474-4f11-ac69-153e12ee0c4f
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: bob
  namespace: default
# kubectl create clusterrolebinding bob-admin --clusterrole=admin --serviceaccount=default:bob -o yaml > 02-bob-admin.yaml