repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io

releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: stable/nginx-ingress
  version: 1.41.3
  wait: true

- name: cert-manager
  needs:
    - nginx-ingress/nginx-ingress
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 1.8.0
  values:
    - installCRDs: true

- name: chartmuseum
  needs:
    - cert-manager/cert-manager
  namespace: chartmuseum
  chart: stable/chartmuseum
  version: 2.13.2
  values:
    - ../chartmuseum/values.yaml
#    - ./issuer.yaml

- name: harbor
  needs:
    - cert-manager/cert-manager
  namespace: harbor
  chart: harbor/harbor
  version: 1.9.0
  values:
    - ../harbor/values.yaml

apiVersions:
- v1
- v2